//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataExchange.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Message { get; set; }
        public string InnerException { get; set; }
        public Nullable<System.DateTime> DateTriggered { get; set; }
    }
}
